cms/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from django.conf import settings
import debug_toolbar

urlpatterns = [
    re_path(r"^__debug__/", include(debug_toolbar.urls)),
    path(settings.DJANGO_ADMIN_URL, admin.site.urls),
    re_path(r"^", include("files.urls")),
    re_path(r"^", include("users.urls")),
    re_path(r"^accounts/", include("allauth.urls")),
    re_path(r"^api-auth/", include("rest_framework.urls")),
]

uploader/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path

from . import views

app_name = "uploader"

urlpatterns = [
    re_path(r"^upload/$", views.FineUploaderView.as_view(), name="upload"),
]

users/urls.py
from django.conf import settings
from django.urls import path, re_path

from . import views

urlpatterns = [
    # NON API VIEWS
    re_path("^user/(?P<username>[\w@._-]*)$", views.view_user, name="get_user"),
    re_path("^user/(?P<username>[\w@._-]*)/$", views.view_user, name="get_user"),
    re_path(
        r"^user/(?P<username>[\w@.]*)/media$",
        views.view_user_media,
        name="get_user_media",
    ),
    re_path(
        r"^user/(?P<username>[\w@.]*)/playlists$",
        views.view_user_playlists,
        name="get_user_playlists",
    ),
    re_path(
        r"^user/(?P<username>[\w@.]*)/about$",
        views.view_user_about,
        name="get_user_about",
    ),
    re_path("^user/(?P<username>[\w@.]*)/edit$", views.edit_user, name="edit_user"),
    re_path(
        r"^channel/(?P<friendly_token>[\w]*)$", views.view_channel, name="view_channel"
    ),
    re_path(
        r"^channel/(?P<friendly_token>[\w]*)/edit$",
        views.edit_channel,
        name="edit_channel",
    ),
    # API VIEWS
    re_path("^api/v1/users$", views.UserList.as_view(), name="api_users"),
    re_path("^api/v1/users/$", views.UserList.as_view()),
    re_path(
        r"^api/v1/users/(?P<username>[\w@._-]*)$",
        views.UserDetail.as_view(),
        name="api_get_user",
    ),
    re_path(
        r"^api/v1/users/(?P<username>[\w@._-]*)/contact",
        views.contact_user,
        name="api_contact_user",
    ),
]

if settings.DEBUG:
    urlpatterns += [
        # problem with start with /
        re_path("^/user/(?P<username>[\w@._-]*)$", views.view_user, name="get_user"),
        re_path("^/user/(?P<username>[\w@._-]*)/$", views.view_user, name="get_user"),
    ]

users/forms.py
from django import forms

from .models import Channel, User


class Date_Input(forms.DateInput):
    input_type = "date"


class MultipleSelect(forms.CheckboxSelectMultiple):
    input_type = "checkbox"


class SignupForm(forms.Form):
    name = forms.CharField(max_length=100, label="Name")

    def signup(self, request, user):
        user.name = self.cleaned_data["name"]
        user.save()
        if self.data.get("subscribe"):
            from files.tasks import subscribe_user

            subscribe_user.delay(user.email, user.name)


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "name",
            "description",
            "email",
            "location_country",
            "home_page",
            "social_media_links",
            "logo",
            "notification_on_comments",
            "is_featured",
            "advancedUser",
            "is_manager",
            "is_editor",
            "allow_contact",
        )

    #        widgets = {
    #           'logo': forms.FileInput(),
    #      }

    def clean_logo(self):
        image = self.cleaned_data.get("logo", False)
        if image:
            if image.size > 2 * 1024 * 1024:
                raise forms.ValidationError("Image file too large ( > 2mb )")
            return image
        else:
            raise forms.ValidationError("Please provide a logo")

    def __init__(self, user, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields.pop("is_featured")
        if not user.is_superuser:
            self.fields.pop("advancedUser")
            self.fields.pop("is_manager")
            self.fields.pop("is_editor")


class ChannelForm(forms.ModelForm):
    class Meta:
        model = Channel
        fields = ("banner_logo",)

    def clean_banner_logo(self):
        image = self.cleaned_data.get("banner_logo", False)
        if image:
            if image.size > 2 * 1024 * 1024:
                raise forms.ValidationError("Image file too large ( > 2mb )")
            return image
        else:
            raise forms.ValidationError("Please provide a banner")

users/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from rest_framework import permissions, status
from rest_framework.decorators import api_view
from rest_framework.exceptions import PermissionDenied
from rest_framework.parsers import (
    FileUploadParser,
    FormParser,
    JSONParser,
    MultiPartParser,
)
from rest_framework.response import Response
from rest_framework.settings import api_settings
from rest_framework.views import APIView

from cms.permissions import IsUserOrManager
from files.lists import video_countries
from files.methods import is_mediacms_editor, is_mediacms_manager

from .forms import ChannelForm, UserForm
from .models import Channel, User
from .serializers import UserDetailSerializer, UserSerializer


def get_user(username):
    try:
        user = User.objects.get(username=username)
        return user
    except User.DoesNotExist:
        return None


def view_user(request, username):
    context = {}
    user = get_user(username=username)
    if not user:
        return HttpResponseRedirect("/members")
    context["user"] = user
    context["CAN_EDIT"] = (
        True
        if ((user and user == request.user) or is_mediacms_manager(request.user))
        else False
    )
    context["CAN_DELETE"] = True if is_mediacms_manager(request.user) else False
    context["SHOW_CONTACT_FORM"] = (
        True if (user.allow_contact or is_mediacms_editor(request.user)) else False
    )

    return render(request, "cms/user.html", context)


def view_user_media(request, username):
    context = {}
    user = get_user(username=username)
    if not user:
        return HttpResponseRedirect("/members")

    context["user"] = user
    context["CAN_EDIT"] = (
        True
        if ((user and user == request.user) or is_mediacms_manager(request.user))
        else False
    )
    context["CAN_DELETE"] = True if is_mediacms_manager(request.user) else False
    context["SHOW_CONTACT_FORM"] = (
        True if (user.allow_contact or is_mediacms_editor(request.user)) else False
    )

    return render(request, "cms/user_media.html", context)


def view_user_playlists(request, username):
    context = {}
    user = get_user(username=username)
    if not user:
        return HttpResponseRedirect("/members")

    context["user"] = user
    context["CAN_EDIT"] = (
        True
        if ((user and user == request.user) or is_mediacms_manager(request.user))
        else False
    )
    context["CAN_DELETE"] = True if is_mediacms_manager(request.user) else False
    context["SHOW_CONTACT_FORM"] = (
        True if (user.allow_contact or is_mediacms_editor(request.user)) else False
    )

    return render(request, "cms/user_playlists.html", context)


def view_user_about(request, username):
    context = {}
    user = get_user(username=username)
    if not user:
        return HttpResponseRedirect("/members")

    context["user"] = user
    context["CAN_EDIT"] = (
        True
        if ((user and user == request.user) or is_mediacms_manager(request.user))
        else False
    )
    context["CAN_DELETE"] = True if is_mediacms_manager(request.user) else False
    context["SHOW_CONTACT_FORM"] = (
        True if (user.allow_contact or is_mediacms_editor(request.user)) else False
    )

    return render(request, "cms/user_about.html", context)


@login_required
def edit_user(request, username):
    user = get_user(username=username)
    if not user or (user != request.user and not is_mediacms_manager(request.user)):
        return HttpResponseRedirect("/")

    if request.method == "POST":
        form = UserForm(request.user, request.POST, request.FILES, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            return HttpResponseRedirect(user.get_absolute_url())
    else:
        form = UserForm(request.user, instance=user)
    return render(request, "cms/user_edit.html", {"form": form})


def view_channel(request, friendly_token):
    context = {}
    channel = Channel.objects.filter(friendly_token=friendly_token).first()
    if not channel:
        user = None
    else:
        user = channel.user
    context["user"] = user
    context["CAN_EDIT"] = (
        True
        if ((user and user == request.user) or request.user.is_superuser)
        else False
    )

    return render(request, "cms/channel.html", context)


@login_required
def edit_channel(request, friendly_token):
    channel = Channel.objects.filter(friendly_token=friendly_token).first()
    if not (
        channel and request.user.is_authenticated and (request.user == channel.user)
    ):
        return HttpResponseRedirect("/")

    if request.method == "POST":
        form = ChannelForm(request.POST, request.FILES, instance=channel)
        if form.is_valid():
            channel = form.save(commit=False)
            channel.save()
            return HttpResponseRedirect(request.user.get_absolute_url())
    else:
        form = ChannelForm(instance=channel)
    return render(request, "cms/channel_edit.html", {"form": form})


@csrf_exempt
@api_view(["POST"])
def contact_user(request, username):
    if not request.user.is_authenticated:
        return Response(
            {"detail": "request need be authenticated"},
            status=status.HTTP_401_UNAUTHORIZED,
        )
    user = User.objects.filter(username=username).first()
    if user and (user.allow_contact or is_mediacms_editor(request.user)):
        form_subject = request.data.get("subject")
        from_email = request.user.email
        subject = f"[{settings.PORTAL_NAME}] - Message from {from_email}"
        body = request.data.get("body")
        body = """
You have received a message through the contact form\n
Sender name: %s
Sender email: %s\n
\n %s
\n %s
""" % (
            request.user.name,
            from_email,
            form_subject,
            body,
        )
        email = EmailMessage(
            subject,
            body,
            settings.DEFAULT_FROM_EMAIL,
            [user.email],
            reply_to=[from_email],
        )
        email.send(fail_silently=True)

    return Response(status=status.HTTP_204_NO_CONTENT)


class UserList(APIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    parser_classes = (JSONParser, MultiPartParser, FormParser, FileUploadParser)

    def get(self, request, format=None):
        pagination_class = api_settings.DEFAULT_PAGINATION_CLASS
        paginator = pagination_class()
        users = (
            User.objects.filter()
            .exclude(username="emnews")
            .order_by("-advancedUser", "-last_published_video_datetime")
        )
        location = request.GET.get("location", "").strip()
        if location:
            location = {value: key for key, value in dict(video_countries).items()}.get(
                location
            )
            users = users.filter(location_country=location)

        page = paginator.paginate_queryset(users, request)

        serializer = UserSerializer(page, many=True, context={"request": request})
        return paginator.get_paginated_response(serializer.data)


class UserDetail(APIView):
    """ """

    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsUserOrManager)
    parser_classes = (JSONParser, MultiPartParser, FormParser, FileUploadParser)

    def get_user(self, username):
        try:
            user = User.objects.get(username=username)
            # this need be explicitly called, and will call
            # has_object_permission() after has_permission has succeeded
            self.check_object_permissions(self.request, user)
            return user
        except PermissionDenied:
            return Response(
                {"detail": "not enough permissions"}, status=status.HTTP_400_BAD_REQUEST
            )
        except User.DoesNotExist:
            return Response(
                {"detail": "user does not exist"}, status=status.HTTP_400_BAD_REQUEST
            )

    def get(self, request, username, format=None):
        # Get user details
        user = self.get_user(username)
        if isinstance(user, Response):
            return user

        serializer = UserDetailSerializer(user, context={"request": request})
        return Response(serializer.data)

    def post(self, request, uid, format=None):
        # USER
        user = self.get_user(uid)
        if isinstance(user, Response):
            return user

        serializer = UserDetailSerializer(
            user, data=request.data, context={"request": request}
        )
        if serializer.is_valid():
            logo = request.data.get("logo")
            if logo:
                serializer.save(logo=logo)
            else:
                serializer.save()

            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def put(self, request, uid, format=None):
        # ADMIN
        user = self.get_user(uid)
        if isinstance(user, Response):
            return user

        if not request.user.is_superuser:
            return Response(
                {"detail": "not allowed"}, status=status.HTTP_400_BAD_REQUEST
            )

        action = request.data.get("action")
        if action == "feature":
            user.is_featured = True
            user.save()
        elif action == "unfeature":
            user.is_featured = False
            user.save()

        serializer = UserDetailSerializer(user, context={"request": request})
        return Response(serializer.data)

    def delete(self, request, username, format=None):
        # Delete a user
        user = self.get_user(username)
        if isinstance(user, Response):

templates/cms/add-media.html
{% extends "base.html" %}
{% load static %}

{% block headtitle %}Add new media - {{PORTAL_NAME}}{% endblock headtitle %}

{% block headermeta %}{% endblock headermeta %}

{% block externallinks %}
{% if LOAD_FROM_CDN %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/file-uploader/5.13.0/fine-uploader.min.js" rel="preload" as="script">
<script src="https://cdnjs.cloudflare.com/ajax/libs/file-uploader/5.13.0/fine-uploader.min.js"></script>
{% else %}
<link href="{% static "lib/file-uploader/5.13.0/fine-uploader.min.js" %}" rel="preload" as="script">
<script src="{% static "lib/file-uploader/5.13.0/fine-uploader.min.js" %}"></script>
{% endif %}
{% endblock externallinks %}

{% block topimports %}
<link href="{% static "css/add-media.css" %}" rel="preload" as="style">
<link href="{% static "css/add-media.css" %}" rel="stylesheet">
{%endblock topimports %}

{% block innercontent %}
{% if request.user.is_authenticated %}

	{% if can_add %}

		<!--enter one or more media files. Limit per file is XXX MBs-->

		<div class="media-uploader-wrap">
			<div class="media-uploader-top-wrap">
				<div class="media-uploader-top-left-wrap">
					<h1>Upload media files</h1>
				</div>
				<div class="media-uploader-top-right-wrap"> </div>
			</div>
			<script type="text/template" id="qq-template">
				<div class="media-uploader-bottom-wrap qq-uploader-selector">
					<div class="media-uploader-bottom-left-wrap">
						<div class="media-drag-drop-wrap">
							<div class="media-drag-drop-inner" qq-drop-area-text="Drop files here">
								<div class="media-drag-drop-content">
									<div class="media-drag-drop-content-inner">
										<span><i class="material-icons">cloud_upload</i></span>
										<span>Drag and drop files</span>
										<span>or</span>
										<span class="browse-files-btn-wrap">
											<span class="qq-upload-button-selector">Browse your files</span>
										</span>
										<div class="qq-upload-drop-area-selector media-dropzone" qq-hide-dropzone>
											<span class="qq-upload-drop-area-text-selector"></span>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="media-uploader-bottom-right-wrap">
						<ul class="media-upload-items-list qq-upload-list-selector">
							<li>
								<div class="media-upload-item-main">
									<div class="media-upload-item-thumb">
										<img class="qq-thumbnail-selector" qq-max-size="120" qq-server-scale alt="" />
										<span class="media-upload-item-spinner qq-upload-spinner-selector"><i class="material-icons">autorenew</i></span>
										<button type="button" class="qq-upload-retry-selector retry-media-upload-item" aria-label="Retry"><i class="material-icons">refresh</i> Retry</button>
									</div>
									<div class="media-upload-item-details">
										<div class="media-upload-item-name">
											<span class="media-upload-item-filename qq-upload-file-selector"></span>
											<input class="media-upload-item-filename-input qq-edit-filename-selector" tab-index="0" type="text" />
										</div>
										<div class="media-upload-item-details-bottom">
											<div class="media-upload-item-progress-bar-container qq-progress-bar-container-selector">
												<div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="media-upload-item-progress-bar qq-progress-bar-selector"></div>
											</div>
											<span class="media-upload-item-upload-size qq-upload-size-selector"></span>
											<span role="status" class="media-upload-item-status-text qq-upload-status-text-selector"></span>
										</div>
										<div class="media-upload-item-top-actions">
											<span class="filename-edit qq-edit-filename-icon-selector" aria-label="Edit filename">Edit filename <i class="material-icons">create</i></span>
											<button type="button" class="delete-media-upload-item qq-upload-delete-selector" aria-label="Delete">Delete <i class="material-icons">delete</i></button>
											<button type="button" class="cancel-media-upload-item qq-upload-cancel-selector" aria-label="Cancel">Cancel <i class="material-icons">cancel</i></button>
											<a href="#" class="view-uploaded-media-link qq-hide" target="_blank">View media <i class="material-icons">open_in_new</i></a>
										</div>
										<div class="media-upload-item-bottom-actions">
											<button type="button" class="continue-media-upload-item qq-upload-continue-selector" aria-label="Continue"><i class="material-icons">play_circle_outline</i> Continue</button>
											<button type="button" class="pause-media-upload-item qq-upload-pause-selector" aria-label="Pause"><i class="material-icons">pause_circle_outline</i> Pause</button>
										</div>
									</div>
								</div>
							</li>
						</ul>
						<dialog style="background-color: white !important" class="qq-alert-dialog-selector">
							<div class="qq-dialog-message-selector"></div>
							<div class="qq-dialog-buttons">
								<button type="button" class="qq-cancel-button-selector">CLOSE</button>
							</div>
						</dialog>
						<dialog class="qq-confirm-dialog-selector">
							<div class="qq-dialog-message-selector"></div>
							<div class="qq-dialog-buttons">
								<button type="button" class="qq-cancel-button-selector">NO</button>
								<button type="button" class="qq-ok-button-selector">YES</button>
							</div>
						</dialog>
						<dialog class="qq-prompt-dialog-selector">
							<div class="qq-dialog-message-selector"></div>
							<input type="text">
							<div class="qq-dialog-buttons">
								<button type="button" class="qq-cancel-button-selector">CANCEL</button>
								<button type="button" class="qq-ok-button-selector">OK</button>
							</div>
						</dialog>
					</div>
				</div>
			</script>
			<div class="media-uploader"></div>
		</div>

	{% else %}

		{{can_upload_exp}}

		<br>

		<a href='/contact'>Contact</a> the admin owners for more information.

	{% endif %}

{% else %}

	<div class="user-action-form-wrap">
		<div class="user-action-form-inner">

			<h1>Sign In</h1>

			Please login or register before you upload a media!

			{% url 'upload_media' as redirect_url %}

			<p>If you have not created an account yet, then please <a href="{% url 'account_signup' %}?next={{ redirect_url }}">sign up</a> first.</p>

			<form class="login" method="POST" action="{% url 'account_login' %}">
				{% csrf_token %}
				{{ form.as_p }}
				<input type="hidden" name="next" value="{{ redirect_url }}" />
				<a class="button secondaryAction" href="{% url 'account_reset_password' %}">Forgot Password?</a>
				<button class="primaryAction" type="submit">Sign In</button>
			</form>

		</div>
	</div>

{% endif %}
{% endblock innercontent %}

{% block bottomimports %}
<script src="{% static "js/add-media.js" %}"></script>
<script>
	document.addEventListener("DOMContentLoaded", function(event) {
		function getCSRFToken() {
			var i, cookies, cookie, cookieVal = null;
			if ( document.cookie && '' !== document.cookie ) {
				cookies = document.cookie.split(';');
				i = 0;
				while( i < cookies.length ){
					cookie = cookies[i].trim();
					if ( 'csrftoken=' === cookie.substring(0, 10) ) {
						cookieVal = decodeURIComponent( cookie.substring(10) );
						break;
					}
					i += 1;
				}
			}
			return cookieVal;
		}
		var default_concurrent_chunked_uploader = new qq.FineUploader({
			debug: false,
			element: document.querySelector('.media-uploader'),
			request: {
				endpoint: '{% url 'uploader:upload' %}',
				customHeaders: {
					'X-CSRFToken': getCSRFToken('csrftoken'),
				},
			},
			retry: {
				enableAuto: true,
				maxAutoAttempts: 2,
			},
			messages: {
                    tooManyItemsError: "You have attempted to upload {netItems} files exceeding the limit. Non-Tusted Users like you can only upload one media at a time.",
				},
			validation: {
				itemLimit: {{UPLOAD_MAX_FILES_NUMBER}},
				sizeLimit: {{UPLOAD_MAX_SIZE}},
			},
			chunking: {
				enabled: true,
				concurrent: {
					enabled: true,
				},
				success: {
					endpoint: '{% url 'uploader:upload' %}?done',
				},
			},
			callbacks: {
				onError: function(id, name, errorReason, xhrOrXdr) {
					console.warn(qq.format("Error on file number {} - {}.  Reason: {}", id, name, errorReason));
				},
				onComplete: function( id, name, response, request ) {

					if( response.success ){

						if( response.media_url ) {
							if( 1 === this._currentItemLimit ) {
								// setTimeout(function(){ window.location.href = response.media_url; }, 500);
								window.location.href = response.media_url.replace("/view?", "/edit?");
								return;
							}
						}
						var listEl = document.querySelector( '.qq-file-id-' + id );
						var viewFileEl = listEl.querySelector( '.view-uploaded-media-link' );

						if( listEl ){
							var fileUrl = response.media_url;
							listEl.style.cursor = 'pointer';
							listEl.addEventListener( 'click', function(ev){
								ev.preventDefault();
								ev.stopPropagation();
								var win = window.open( fileUrl, '_blank' );
								win.focus();
							});
						}

						if( viewFileEl ){
							viewFileEl.setAttribute( 'href', response.media_url );
							viewFileEl.setAttribute( 'class', 'view-uploaded-media-link' );
						}
					}
				},
			},
		});
	});
</script>
{% endblock bottomimports %}

templates/cms/add_subtitle.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block headtitle %}Add subtitle - {{PORTAL_NAME}}{% endblock headtitle %}

{% block headermeta %}{% endblock headermeta %}

{% block innercontent %}
	<div class="user-action-form-wrap">
		<h1>Add Subtitle/CC</h1>
		<div class="user-action-form-inner">
			Media: <a href="{{media.get_absolute_url}}">{{media.title}}</a>
			<form enctype="multipart/form-data" action="" method="post" class="post-form">
				{% csrf_token %}
				{{ form|crispy }}
				<button class="primaryAction" type="submit">Add</button>
			</form>


			{% if subtitles %}
				<h2>View/Edit Existing Subtitles</h2>
				<ul>
					{% for subtitle in subtitles %}
						<li><a href="{{subtitle.url}}">{{subtitle.language.title}}</a></li>
					{% endfor %}
				</ul>
			{% endif %}
		</div>

	</div>


<script>
	// increase titles
	const field_labels = document.querySelectorAll('label');
	field_labels.forEach((label) => {
		label.style.fontSize = '140%';
		label.style.fontWeight = 'bold';

	});

	bengaliCustomMessageShown = false;
    document.getElementById('id_language').addEventListener('change', function() {
		if (bengaliCustomMessageShown) {
			return;
		} else {

			const selectedText = this.options[this.selectedIndex].text;
			if (selectedText === "Bengali") {
				const subtitleDiv = document.getElementById('hint_id_subtitle_file');
				const message = document.createElement('div');
				message.id = 'bengali-message';
				message.textContent = 'Bengali text works best with Safari/Firefox.';
				subtitleDiv.appendChild(message);
				bengaliCustomMessageShown = true;
			}
		}
    });

</script>



{% endblock innercontent %}

templates/cms/categories.html
{% extends "base.html" %}
{% load static %}

{% block headtitle %}Categories - {{PORTAL_NAME}}{% endblock headtitle %}

{% block headermeta %}

<meta property="og:title" content="Categories - {{PORTAL_NAME}}">
<meta property="og:type" content="website">
<meta property="og:description" content="">

<meta property="og:image" content="{{FRONTEND_HOST}}/media/userlogos/cinemata_share_banner-01.png">
<meta name="twitter:card" content="summary_large_image">

<script type="application/ld+json">
{
	"@context": "https://schema.org",
	"@type": "BreadcrumbList",
	"itemListElement": [{
		"@type": "ListItem",
		"position": 1,
        "name": "{{PORTAL_NAME}}",
        "item": {
			"@type": "WebPage",
	        "@id": "{{FRONTEND_HOST}}"
	    }
    },
    {
		"@type": "ListItem",
		"position": 2,
        "name": "Categories",
        "item": {
            "@type": "WebPage",
            "@id": "{{FRONTEND_HOST}}/categories"
        }
    }]
}
</script>

{% endblock headermeta %}

{% block content %}<div id="page-categories"></div>{% endblock %}

{% block bottomimports %}
<script src="{% static "js/categories.js" %}"></script>
{% endblock bottomimports %}

templates/cms/channel.html
{% extends "base.html" %}
{% load static %}

{% block headtitle %}{% if user.name %}{{user.name}} - {% endif %}{{PORTAL_NAME}}{% endblock headtitle %}

{% block headermeta %}

<meta property="og:title" content="{% if user.name %}{{user.name}} - {% endif %}{{PORTAL_NAME}}">
<meta property="og:type" content="website">
<meta property="og:description" content="">

<meta name="twitter:card" content="summary">

{% endblock headermeta %}

{% block innercontent %}
{% if user %}{% else %}
No such user
{% endif %}
{% endblock %}

{% block content %}
{% if user %}<div id="page-profile-home"></div>{% endif %}
{% endblock %}

{% block bottomimports %}
<script src="{% static "js/profile-home.js" %}"></script>
{% endblock bottomimports %}

templates/cms/edit_subtitle.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block headtitle %}Edit subtitle - {{PORTAL_NAME}}{% endblock headtitle %}

{% block headermeta %}{% endblock headermeta %}

{% block innercontent %}

	{% if action == 'delete' %}

	<div class="user-action-form-wrap">
		<h1>Confirm deletion</h1>

		<div class="user-action-form-inner">
			are you sure you want to delete the subtitle?

			<form action="{{subtitle.url}}&action=delete&confirm=true" method="post" class="post-form">
				{% csrf_token %}
				<button class="secondaryAction" type="submit">DELETE SUBTITLE</button>
			</form>
		</div>

	</div>



	{% else %}

	<div class="user-action-form-wrap">
		<h1>Edit {{subtitle.language.title}} subtitle</h1>
		<div class="user-action-form-inner">
			Media: <a href="{{subtitle.media.get_absolute_url}}">{{subtitle.media.title}}</a>
			<form action="" method="post" class="post-form">
				{% csrf_token %}
				{{ form|crispy }}
				<button class="primaryAction" style="margin-right: 10px" type="submit">SAVE</button>
				<button class="primaryAction" style="margin-right: 10px" type="button" onclick="window.location.href='{{subtitle.url}}&action=download';">DOWNLOAD</button>
				<button class="primaryAction" type="button" onclick="window.location.href='{{subtitle.url}}&action=delete';">DELETE</button>

			</form>
		</div>

	</div>

	{% endif %}
{% endblock innercontent %}

templates/cms/search.html
{% extends "base.html" %}
{% load static %}
{% block headermeta %}{% endblock headermeta %}

{% block content %}
{% if user %}<div id="page-search"></div>{% endif %}
{% endblock %}

{% block bottomimports %}
<script src="{% static "js/search.js" %}"></script>
{% endblock bottomimports %}